"""Project workspace, knowledge management and reports."""
from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import or_
from sqlalchemy.orm import Session

from ..database import get_db
from ..models import KnowledgeItem, Project, Report
from ..schemas import (
    KnowledgeCreate,
    KnowledgeOut,
    ProjectCreate,
    ProjectOut,
    ReportCreate,
    ReportOut,
)
from ..security import CurrentUser

router = APIRouter(tags=["work"])

Db = Annotated[Session, Depends(get_db)]


# ---------- workspace / projects ----------
@router.get("/projects", response_model=list[ProjectOut])
def list_projects(db: Db, user: CurrentUser) -> list[Project]:
    return db.query(Project).order_by(Project.updated_at.desc()).all()


@router.post("/projects", response_model=ProjectOut)
def create_project(body: ProjectCreate, db: Db, user: CurrentUser) -> Project:
    project = Project(
        name=body.name,
        lead=body.lead or user.full_name,
        stage=body.stage,
        status="In progress",
        dataset_count=0,
    )
    db.add(project)
    db.commit()
    db.refresh(project)
    return project


@router.get("/projects/{project_id}", response_model=ProjectOut)
def project_detail(project_id: int, db: Db, user: CurrentUser) -> Project:
    project = db.get(Project, project_id)
    if project is None:
        raise HTTPException(status_code=404, detail="Project not found")
    return project


# ---------- knowledge hub ----------
@router.get("/knowledge", response_model=list[KnowledgeOut])
def list_knowledge(
    db: Db,
    user: CurrentUser,
    item_type: str = "",
    q: str = "",
) -> list[KnowledgeItem]:
    query = db.query(KnowledgeItem)
    if item_type:
        query = query.filter(KnowledgeItem.item_type == item_type)
    if q:
        like = f"%{q.lower()}%"
        query = query.filter(
            or_(KnowledgeItem.title.ilike(like), KnowledgeItem.summary.ilike(like))
        )
    return query.order_by(KnowledgeItem.created_at.desc()).all()


@router.post("/knowledge", response_model=KnowledgeOut)
def create_knowledge(body: KnowledgeCreate, db: Db, user: CurrentUser) -> KnowledgeItem:
    item = KnowledgeItem(**body.model_dump())
    db.add(item)
    db.commit()
    db.refresh(item)
    return item


# ---------- reports ----------
@router.get("/reports", response_model=list[ReportOut])
def list_reports(db: Db, user: CurrentUser) -> list[Report]:
    return db.query(Report).order_by(Report.generated_at.desc()).all()


@router.post("/reports/generate", response_model=ReportOut)
def generate_report(body: ReportCreate, db: Db, user: CurrentUser) -> Report:
    report = Report(
        title=body.title,
        source=body.source or f"Generated by {user.full_name}",
        format=body.format,
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report
