import * as Joi from "joi";

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid("development", "test", "staging", "production").default("development"),
  PORT: Joi.number().port().default(4000),
  LOG_LEVEL: Joi.string().valid("trace", "debug", "info", "warn", "error").default("info"),
  API_URL: Joi.string().uri().required(),
  STORE_URL: Joi.string().uri().required(),
  ADMIN_URL: Joi.string().uri().required(),
  CORS_ORIGINS: Joi.string().required(),
  DATABASE_URL: Joi.string().uri().required(),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_TTL_SECONDS: Joi.number().default(900),
  JWT_REFRESH_TTL_DAYS: Joi.number().default(30),
  THROTTLE_TTL_MS: Joi.number().default(60000),
  THROTTLE_LIMIT: Joi.number().default(100),
  FIRST_ADMIN_EMAIL: Joi.string().email().required(),
  FIRST_ADMIN_PASSWORD: Joi.string().min(8).required(),
  EMAIL_PROVIDER: Joi.string().default("console"),
  SMS_PROVIDER: Joi.string().default("console"),
  REDIS_URL: Joi.string().allow("").default(""),
  TYPESENSE_HOST: Joi.string().allow("").default(""),
  TYPESENSE_PORT: Joi.number().port().default(8108),
  TYPESENSE_PROTOCOL: Joi.string().valid("http", "https").default("https"),
  TYPESENSE_ADMIN_API_KEY: Joi.string().allow("").default(""),
  TYPESENSE_SEARCH_API_KEY: Joi.string().allow("").default(""),
  TYPESENSE_COLLECTION: Joi.string().default("products"),
  RAZORPAY_KEY_ID: Joi.string().allow("").default(""),
  RAZORPAY_KEY_SECRET: Joi.string().allow("").default(""),
  RAZORPAY_WEBHOOK_SECRET: Joi.string().allow("").default(""),
  PAYMENT_PROVIDER: Joi.string().valid("auto", "mock", "razorpay").default("auto"),
});